"""empty message

Revision ID: cbcc91ade90e
Revises: a9e4b81340b0
Create Date: 2024-06-08 13:03:28.262186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbcc91ade90e'
down_revision = 'a9e4b81340b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('two_factor')
        batch_op.drop_column('two_factor_recovery_codes')
        batch_op.drop_column('two_factor_secret')
        batch_op.drop_column('two_factor_recovery')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('two_factor_recovery', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('two_factor_secret', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('two_factor_recovery_codes', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('two_factor', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
