"""empty message

Revision ID: 009c7b7e19be
Revises: 6a53a8c267eb
Create Date: 2024-06-19 16:20:32.769036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009c7b7e19be'
down_revision = '6a53a8c267eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user_historic',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('is_logged_in', sa.Boolean(), nullable=True),
    sa.Column('date_logged_in', sa.DateTime(), nullable=True),
    sa.Column('date_logged_out', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('two_fa_auth',
    sa.Column('two_fa_id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('two_factor_auth_secret', sa.String(length=100), nullable=False),
    sa.Column('method_auth', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_exp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('two_fa_id')
    )
    op.create_table('user_token',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_exp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('users',
    sa.Column('userID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=6), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_token')
    op.drop_table('two_fa_auth')
    op.drop_table('auth_user_historic')
    # ### end Alembic commands ###
