"""empty message

Revision ID: 00a0dd3f183b
Revises: 907771064e6a
Create Date: 2024-06-29 13:08:10.471135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a0dd3f183b'
down_revision = '907771064e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_user_historic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime_logged_in', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('datetime_added', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_token', schema=None) as batch_op:
        batch_op.drop_column('datetime_added')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('auth_user_historic', schema=None) as batch_op:
        batch_op.drop_column('datetime_logged_in')

    # ### end Alembic commands ###
