"""empty message

Revision ID: 09703f729179
Revises: 3d3ced1ba6ec
Create Date: 2024-07-01 14:20:26.191690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09703f729179'
down_revision = '3d3ced1ba6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('datetime_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('subscriber_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    # ### end Alembic commands ###
