"""empty message

Revision ID: 16102f2cc7e0
Revises: 545f8834e3ae
Create Date: 2024-07-23 22:49:41.244597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16102f2cc7e0'
down_revision = '545f8834e3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_date_added',
               existing_type=sa.DATE(),
               type_=sa.String(length=11),
               existing_nullable=True)
        batch_op.alter_column('product_datetime_added',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('product_date_updated',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_quantity', sa.Integer(), nullable=True))
        batch_op.alter_column('stock_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('product_sale_price')
        batch_op.drop_column('product_discount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_discount', sa.DOUBLE(), nullable=True))
        batch_op.add_column(sa.Column('product_sale_price', sa.DOUBLE(), nullable=True))
        batch_op.alter_column('stock_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('product_quantity')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_date_updated',
               existing_type=sa.String(length=20),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('product_datetime_added',
               existing_type=sa.String(length=20),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('product_date_added',
               existing_type=sa.String(length=11),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
