"""empty message

Revision ID: 1a94e56a3eeb
Revises: c96de806bfc0
Create Date: 2024-11-28 18:27:39.407538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a94e56a3eeb'
down_revision = 'c96de806bfc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HelpMessage', schema=None) as batch_op:
        batch_op.alter_column('date_added',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('datetime_added',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HelpMessage', schema=None) as batch_op:
        batch_op.alter_column('datetime_added',
               existing_type=sa.String(length=30),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('date_added',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
