"""empty message

Revision ID: 1c9f302abe53
Revises: 3113c04296d3
Create Date: 2024-09-11 12:11:17.085140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9f302abe53'
down_revision = '3113c04296d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('transaction_code', sa.String(length=30), nullable=False),
    sa.Column('trans_from', sa.String(length=50), nullable=False),
    sa.Column('trans_to', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.String(length=11), nullable=True),
    sa.Column('year_added', sa.String(length=4), nullable=True),
    sa.Column('month_added', sa.String(length=20), nullable=True),
    sa.Column('timestamp_added', sa.String(length=20), nullable=True),
    sa.Column('update_added', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('transaction_code')
    )
    op.create_table('payment_card',
    sa.Column('card_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=100), nullable=True),
    sa.Column('card_name', sa.String(length=100), nullable=True),
    sa.Column('card_exp', sa.String(length=100), nullable=True),
    sa.Column('card_cvv', sa.String(length=100), nullable=True),
    sa.Column('card_date_added', sa.String(length=11), nullable=True),
    sa.Column('card_year_added', sa.String(length=4), nullable=True),
    sa.Column('card_month_added', sa.String(length=20), nullable=True),
    sa.Column('card_timestamp_added', sa.String(length=20), nullable=True),
    sa.Column('card_update_added', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('card_id'),
    sa.UniqueConstraint('card_number')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_status', sa.Boolean(), nullable=True))
        batch_op.alter_column('course_details',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('enrolls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_firstname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('student_lastname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('student_address', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('student_address2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('same_address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('save_info', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('student_country', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('student_state', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('student_zip', sa.String(length=10), nullable=False))
        batch_op.alter_column('student_id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('enroll_obs',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('course_description')
        batch_op.drop_column('course_code')
        batch_op.drop_column('student_name')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('card_number', sa.String(length=100), nullable=True))
        batch_op.drop_column('customer_card_name')
        batch_op.drop_column('customer_card_exp')
        batch_op.drop_column('customer_firstname')
        batch_op.drop_column('customer_payment_reference')
        batch_op.drop_column('customer_card_number')
        batch_op.drop_column('customer_lastname')
        batch_op.drop_column('customer_card_cvv')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_card_cvv', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('customer_lastname', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('customer_card_number', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('customer_payment_reference', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('customer_firstname', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('customer_card_exp', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('customer_card_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('card_number')
        batch_op.drop_column('payment_reference')
        batch_op.drop_column('student_id')

    with op.batch_alter_table('enrolls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('course_code', sa.VARCHAR(length=40), nullable=False))
        batch_op.add_column(sa.Column('course_description', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('enroll_obs',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.drop_column('student_zip')
        batch_op.drop_column('student_state')
        batch_op.drop_column('student_country')
        batch_op.drop_column('save_info')
        batch_op.drop_column('same_address')
        batch_op.drop_column('student_address2')
        batch_op.drop_column('student_address')
        batch_op.drop_column('student_lastname')
        batch_op.drop_column('student_firstname')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('course_details',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('course_status')

    op.drop_table('payment_card')
    op.drop_table('card_transactions')
    # ### end Alembic commands ###
