"""empty message

Revision ID: 1cddf32c5dbf
Revises: 1fe463a0fef6
Create Date: 2024-08-20 13:14:30.075085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cddf32c5dbf'
down_revision = '1fe463a0fef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_has_price')
    with op.batch_alter_table('product_price', schema=None) as batch_op:
        batch_op.alter_column('sale_price_01',
               existing_type=sa.DOUBLE(),
               nullable=False)
        batch_op.drop_column('unitary_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unitary_price', sa.DOUBLE(), nullable=False))
        batch_op.alter_column('sale_price_01',
               existing_type=sa.DOUBLE(),
               nullable=True)

    op.create_table('product_has_price',
    sa.Column('price_id', sa.INTEGER(), nullable=False),
    sa.Column('product_barcode', sa.VARCHAR(length=100), nullable=False),
    sa.Column('unitary_price', sa.DOUBLE(), nullable=True),
    sa.Column('sale_price_1', sa.DOUBLE(), nullable=True),
    sa.Column('sale_price_2', sa.DOUBLE(), nullable=True),
    sa.Column('sale_price_with_iva', sa.DOUBLE(), nullable=True),
    sa.Column('sale_pos_price', sa.DOUBLE(), nullable=True),
    sa.Column('price_date_added', sa.VARCHAR(length=11), nullable=True),
    sa.Column('price_year_added', sa.VARCHAR(length=4), nullable=True),
    sa.Column('price_month_added', sa.VARCHAR(length=20), nullable=True),
    sa.Column('price_datetime_added', sa.VARCHAR(length=20), nullable=True),
    sa.Column('price_date_updated', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('price_id')
    )
    # ### end Alembic commands ###
