"""empty message

Revision ID: 1fe463a0fef6
Revises: 8cf96c9497d6
Create Date: 2024-08-05 13:38:50.668738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe463a0fef6'
down_revision = '8cf96c9497d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_has_price',
    sa.Column('price_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_barcode', sa.String(length=100), nullable=False),
    sa.Column('unitary_price', sa.Double(), nullable=True),
    sa.Column('sale_price_1', sa.Double(), nullable=True),
    sa.Column('sale_price_2', sa.Double(), nullable=True),
    sa.Column('sale_price_with_iva', sa.Double(), nullable=True),
    sa.Column('sale_pos_price', sa.Double(), nullable=True),
    sa.Column('price_date_added', sa.String(length=11), nullable=True),
    sa.Column('price_year_added', sa.String(length=4), nullable=True),
    sa.Column('price_month_added', sa.String(length=20), nullable=True),
    sa.Column('price_datetime_added', sa.String(length=20), nullable=True),
    sa.Column('price_date_updated', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('price_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_has_price')
    # ### end Alembic commands ###
