"""empty message

Revision ID: 2244d76c75ca
Revises: 9f958920eefc
Create Date: 2024-05-31 18:22:19.677587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2244d76c75ca'
down_revision = '9f958920eefc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_users')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_auth_secret', sa.String(length=200), nullable=False))
        batch_op.drop_column('two_factor_auth_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_auth_code', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('two_factor_auth_secret')

    op.create_table('_alembic_tmp_users',
    sa.Column('userID', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('country', sa.VARCHAR(length=20), nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=6), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('date_added', sa.DATETIME(), nullable=True),
    sa.Column('date_updated', sa.DATETIME(), nullable=True),
    sa.Column('two_factor_auth_secret', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('userID')
    )
    # ### end Alembic commands ###
