"""empty message

Revision ID: 2bd880ba2861
Revises: 09703f729179
Create Date: 2024-07-01 14:27:18.721514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd880ba2861'
down_revision = '09703f729179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_added', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('month_added', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_column('month_added')
        batch_op.drop_column('year_added')

    # ### end Alembic commands ###
