"""empty message

Revision ID: 3113c04296d3
Revises: 29dd0dcc36c5
Create Date: 2024-09-03 13:46:19.687599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3113c04296d3'
down_revision = '29dd0dcc36c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_code', sa.String(length=100), nullable=False),
    sa.Column('course_description', sa.String(length=100), nullable=False),
    sa.Column('course_details', sa.String(length=100), nullable=False),
    sa.Column('course_date_added', sa.String(length=11), nullable=True),
    sa.Column('course_year_added', sa.String(length=4), nullable=True),
    sa.Column('course_month_added', sa.String(length=20), nullable=True),
    sa.Column('course_timestamp_added', sa.String(length=20), nullable=True),
    sa.Column('course_update_added', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_code')
    )
    op.create_table('enrolls',
    sa.Column('enroll_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enroll_code', sa.String(length=40), nullable=False),
    sa.Column('student_id', sa.String(length=30), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('course_code', sa.String(length=40), nullable=False),
    sa.Column('course_description', sa.String(length=100), nullable=False),
    sa.Column('enroll_status', sa.Boolean(), nullable=True),
    sa.Column('enroll_obs', sa.String(length=100), nullable=False),
    sa.Column('enroll_date_added', sa.String(length=11), nullable=True),
    sa.Column('enroll_year_added', sa.String(length=4), nullable=True),
    sa.Column('enroll_month_added', sa.String(length=20), nullable=True),
    sa.Column('enroll_timestamp_added', sa.String(length=20), nullable=True),
    sa.Column('enroll_update_added', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('enroll_id'),
    sa.UniqueConstraint('enroll_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrolls')
    op.drop_table('courses')
    # ### end Alembic commands ###
