"""empty message

Revision ID: 3919f07d11fa
Revises: f5ab7c5044b7
Create Date: 2024-06-03 17:00:01.784741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3919f07d11fa'
down_revision = 'f5ab7c5044b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
