"""empty message

Revision ID: 43ce86a23fa9
Revises: 9acc62f581e6
Create Date: 2024-05-30 16:37:51.951354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ce86a23fa9'
down_revision = '9acc62f581e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('country_code', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('two_factor_auth_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_updated', sa.DateTime(), nullable=True))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('date_updated')
        batch_op.drop_column('date_added')
        batch_op.drop_column('two_factor_auth_code')
        batch_op.drop_column('phone')
        batch_op.drop_column('country_code')
        batch_op.drop_column('country')
        batch_op.drop_column('email')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
