"""empty message

Revision ID: 545f8834e3ae
Revises: c2e5a24318b9
Create Date: 2024-07-22 13:59:56.585053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545f8834e3ae'
down_revision = 'c2e5a24318b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_quantity', sa.Integer(), nullable=True))
        batch_op.alter_column('stock_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('product_sale_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_sale_price', sa.DOUBLE(), nullable=True))
        batch_op.alter_column('stock_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('product_quantity')

    # ### end Alembic commands ###
