"""empty message

Revision ID: 58a54452e64d
Revises: 1a94e56a3eeb
Create Date: 2024-11-28 19:26:49.108188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a54452e64d'
down_revision = '1a94e56a3eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HelpMessage', schema=None) as batch_op:
        batch_op.alter_column('date_updated',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HelpMessage', schema=None) as batch_op:
        batch_op.alter_column('date_updated',
               existing_type=sa.String(length=30),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
