"""empty message

Revision ID: 62de5e46b0c6
Revises: 58a54452e64d
Create Date: 2024-11-29 02:33:54.910769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62de5e46b0c6'
down_revision = '58a54452e64d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_message',
    sa.Column('h_message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_added', sa.String(length=20), nullable=True),
    sa.Column('datetime_added', sa.String(length=30), nullable=True),
    sa.Column('date_updated', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('h_message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('help_message')
    # ### end Alembic commands ###
