"""empty message

Revision ID: 658c0f13a55d
Revises: 16102f2cc7e0
Create Date: 2024-07-23 23:49:30.669213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658c0f13a55d'
down_revision = '16102f2cc7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('product_unitary_price',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Double(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('product_unitary_price',
               existing_type=sa.Double(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
