"""empty message

Revision ID: 863ee4421e8a
Revises: b3917b549154
Create Date: 2024-06-12 17:35:25.188320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863ee4421e8a'
down_revision = 'b3917b549154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('two_fa_auth',
    sa.Column('two_fa_id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('two_factor_auth_secret', sa.String(length=100), nullable=False),
    sa.Column('method_auth', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_exp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('two_fa_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('two_fa_auth')
    # ### end Alembic commands ###
