"""empty message

Revision ID: 8cf96c9497d6
Revises: 658c0f13a55d
Create Date: 2024-07-24 09:33:52.555367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf96c9497d6'
down_revision = '658c0f13a55d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('product_unitary_price',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Double(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('product_unitary_price',
               existing_type=sa.Double(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
