"""empty message

Revision ID: 907771064e6a
Revises: 1e6664113e54
Create Date: 2024-06-26 23:39:30.796219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907771064e6a'
down_revision = '1e6664113e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_user_historic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime_logged_in', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_user_historic', schema=None) as batch_op:
        batch_op.drop_column('datetime_logged_in')

    # ### end Alembic commands ###
