"""empty message

Revision ID: 95f49d28ab35
Revises: bd0fb2ed3e24
Create Date: 2024-09-28 14:59:07.772436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f49d28ab35'
down_revision = 'bd0fb2ed3e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses_content',
    sa.Column('course_content_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.String(length=100), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('content_module', sa.String(length=100), nullable=True),
    sa.Column('content_file', sa.String(length=100), nullable=False),
    sa.Column('content_description', sa.String(length=100), nullable=True),
    sa.Column('content_thumbnail', sa.String(length=255), nullable=True),
    sa.Column('content_status', sa.Boolean(), nullable=True),
    sa.Column('content_date_added', sa.String(length=11), nullable=True),
    sa.Column('content_year_added', sa.String(length=4), nullable=True),
    sa.Column('content_month_added', sa.String(length=20), nullable=True),
    sa.Column('content_timestamp_added', sa.String(length=20), nullable=True),
    sa.Column('content_update_added', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('course_content_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses_content')
    # ### end Alembic commands ###
