"""empty message

Revision ID: 97981551d638
Revises: 00a0dd3f183b
Create Date: 2024-06-29 13:22:39.003818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97981551d638'
down_revision = '00a0dd3f183b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime_added', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('datetime_added')

    # ### end Alembic commands ###
