"""empty message

Revision ID: b30e4e9e1499
Revises: 
Create Date: 2024-09-23 13:26:36.828464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30e4e9e1499'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_total_lessons', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('course_total_quizzes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('course_total_labs', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('course_total_labs')
        batch_op.drop_column('course_total_quizzes')
        batch_op.drop_column('course_total_lessons')

    # ### end Alembic commands ###
