"""empty message

Revision ID: b5c39e63a46c
Revises: 2bd880ba2861
Create Date: 2024-07-01 21:38:04.511377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c39e63a46c'
down_revision = '2bd880ba2861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('year_added', sa.String(length=5), nullable=True),
    sa.Column('month_added', sa.String(length=10), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('datetime_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('subscriber_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    # ### end Alembic commands ###
