"""empty message

Revision ID: bd0fb2ed3e24
Revises: acff95146f39
Create Date: 2024-09-23 22:50:43.639324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0fb2ed3e24'
down_revision = 'acff95146f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_total_modules', sa.Integer(), nullable=True))

    with op.batch_alter_table('courses_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_module', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses_content', schema=None) as batch_op:
        batch_op.drop_column('content_module')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('course_total_modules')

    # ### end Alembic commands ###
