"""empty message

Revision ID: df35459da1f7
Revises: 
Create Date: 2025-02-03 16:56:13.582772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df35459da1f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('transaction_code', sa.String(length=30), nullable=False),
    sa.Column('trans_from', sa.String(length=50), nullable=False),
    sa.Column('trans_to', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.String(length=11), nullable=True),
    sa.Column('year_added', sa.String(length=4), nullable=True),
    sa.Column('month_added', sa.String(length=20), nullable=True),
    sa.Column('timestamp_added', sa.String(length=50), nullable=True),
    sa.Column('update_added', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('transaction_code')
    )
    op.create_table('course_progress',
    sa.Column('course_progress_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('total_lesson_completed', sa.Integer(), nullable=True),
    sa.Column('last_lesson_completed', sa.String(length=200), nullable=True),
    sa.Column('date_added', sa.String(length=11), nullable=True),
    sa.Column('year_added', sa.String(length=4), nullable=True),
    sa.Column('month_added', sa.String(length=20), nullable=True),
    sa.Column('timestamp_added', sa.String(length=20), nullable=True),
    sa.Column('update_added', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('course_progress_id'),
    sa.UniqueConstraint('course_id')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_code', sa.String(length=100), nullable=False),
    sa.Column('course_description', sa.String(length=100), nullable=False),
    sa.Column('course_level', sa.String(length=100), nullable=False),
    sa.Column('course_details', sa.String(length=100), nullable=True),
    sa.Column('course_image', sa.String(length=255), nullable=True),
    sa.Column('course_view_url', sa.String(length=200), nullable=True),
    sa.Column('course_status', sa.Boolean(), nullable=True),
    sa.Column('course_is_certified', sa.Boolean(), nullable=True),
    sa.Column('course_total_lessons', sa.Integer(), nullable=True),
    sa.Column('course_total_quizzes', sa.Integer(), nullable=True),
    sa.Column('course_total_labs', sa.Integer(), nullable=True),
    sa.Column('course_total_modules', sa.Integer(), nullable=True),
    sa.Column('course_payment_link', sa.String(length=255), nullable=True),
    sa.Column('course_date_added', sa.String(length=11), nullable=True),
    sa.Column('course_year_added', sa.String(length=4), nullable=True),
    sa.Column('course_month_added', sa.String(length=20), nullable=True),
    sa.Column('course_timestamp_added', sa.String(length=20), nullable=True),
    sa.Column('course_update_added', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_code')
    )
    op.create_table('courses_content',
    sa.Column('course_content_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.String(length=100), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('content_module', sa.String(length=100), nullable=True),
    sa.Column('content_file', sa.String(length=100), nullable=False),
    sa.Column('content_description', sa.String(length=100), nullable=True),
    sa.Column('content_thumbnail', sa.String(length=255), nullable=True),
    sa.Column('content_status', sa.Boolean(), nullable=True),
    sa.Column('content_date_added', sa.String(length=11), nullable=True),
    sa.Column('content_year_added', sa.String(length=4), nullable=True),
    sa.Column('content_month_added', sa.String(length=20), nullable=True),
    sa.Column('content_timestamp_added', sa.String(length=20), nullable=True),
    sa.Column('content_update_added', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('course_content_id')
    )
    op.create_table('enrolls',
    sa.Column('enroll_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enroll_code', sa.String(length=40), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_firstname', sa.String(length=100), nullable=False),
    sa.Column('student_lastname', sa.String(length=100), nullable=False),
    sa.Column('student_address', sa.String(length=100), nullable=False),
    sa.Column('student_address2', sa.String(length=100), nullable=True),
    sa.Column('same_address', sa.String(length=100), nullable=True),
    sa.Column('save_info', sa.String(length=100), nullable=True),
    sa.Column('student_country', sa.String(length=100), nullable=False),
    sa.Column('student_state', sa.String(length=100), nullable=False),
    sa.Column('student_zip', sa.String(length=10), nullable=False),
    sa.Column('enroll_type', sa.String(length=50), nullable=True),
    sa.Column('enroll_status', sa.Boolean(), nullable=True),
    sa.Column('enroll_obs', sa.String(length=100), nullable=True),
    sa.Column('enroll_date_added', sa.String(length=11), nullable=True),
    sa.Column('enroll_year_added', sa.String(length=4), nullable=True),
    sa.Column('enroll_month_added', sa.String(length=20), nullable=True),
    sa.Column('enroll_timestamp_added', sa.String(length=20), nullable=True),
    sa.Column('enroll_update_added', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('enroll_id'),
    sa.UniqueConstraint('enroll_code')
    )
    op.create_table('help_message',
    sa.Column('h_message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_added', sa.String(length=20), nullable=True),
    sa.Column('datetime_added', sa.String(length=30), nullable=True),
    sa.Column('date_updated', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('h_message_id')
    )
    op.create_table('payment_card',
    sa.Column('card_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=100), nullable=True),
    sa.Column('card_name', sa.String(length=100), nullable=True),
    sa.Column('card_exp', sa.String(length=20), nullable=True),
    sa.Column('card_cvv', sa.String(length=10), nullable=True),
    sa.Column('card_date_added', sa.String(length=11), nullable=True),
    sa.Column('card_year_added', sa.String(length=4), nullable=True),
    sa.Column('card_month_added', sa.String(length=20), nullable=True),
    sa.Column('card_timestamp_added', sa.String(length=50), nullable=True),
    sa.Column('card_update_added', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('card_id'),
    sa.UniqueConstraint('card_number')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('payment_code', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('card_number', sa.String(length=100), nullable=True),
    sa.Column('payment_date_added', sa.String(length=10), nullable=True),
    sa.Column('payment_year_added', sa.String(length=10), nullable=True),
    sa.Column('payment_month_added', sa.String(length=20), nullable=True),
    sa.Column('payment_timestamp_added', sa.String(length=50), nullable=True),
    sa.Column('payment_update_added', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('payment_code')
    )
    op.create_table('subscribers',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('year_added', sa.String(length=5), nullable=True),
    sa.Column('month_added', sa.String(length=10), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('datetime_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('subscriber_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    op.drop_table('payments')
    op.drop_table('payment_card')
    op.drop_table('help_message')
    op.drop_table('enrolls')
    op.drop_table('courses_content')
    op.drop_table('courses')
    op.drop_table('course_progress')
    op.drop_table('card_transactions')
    # ### end Alembic commands ###
