"""empty message

Revision ID: f5ab7c5044b7
Revises: cbc76ff230a2
Create Date: 2024-06-01 12:52:25.905103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ab7c5044b7'
down_revision = 'cbc76ff230a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DimDate')
    op.drop_table('softcartDimItem')
    op.drop_table('DimCategory')
    op.drop_table('DimCountry')
    op.drop_table('FactSales')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FactSales',
    sa.Column('orderid', sa.CHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('dateid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('countryid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categoryid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('DimCountry',
    sa.Column('countryid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('country', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('countryid', name='DimCountry_pkey')
    )
    op.create_table('DimCategory',
    sa.Column('categoryid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('categoryid', name='DimCategory_pkey')
    )
    op.create_table('softcartDimItem',
    sa.Column('itemid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('itemid', name='softcartDimItem_pkey')
    )
    op.create_table('DimDate',
    sa.Column('dateid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.CHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quarter ', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quarterName', sa.String(), autoincrement=False, nullable=True),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('monthName', sa.CHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weekDay', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weekDayName', sa.CHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('dateid', name='DimDate_pkey')
    )
    # ### end Alembic commands ###
