"""empty message

Revision ID: f73a77cab4dd
Revises: d29f999fbb73
Create Date: 2024-06-17 01:32:26.715917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73a77cab4dd'
down_revision = 'd29f999fbb73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user_historic',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('is_logged_in', sa.Boolean(), nullable=True),
    sa.Column('date_logged_in', sa.DateTime(), nullable=True),
    sa.Column('date_logged_out', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('auth_id')
    )
    with op.batch_alter_table('user_token', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_token', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('auth_user_historic')
    # ### end Alembic commands ###
